
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 23 13:06:25 CST 2020
//----------------------------------------------------

package animaciones.Analizadores.Sintactico;

/** CUP generated class containing symbol constants. */
public class SimbolosTiempo {
  /* terminals */
  public static final int DURACION = 3;
  public static final int Entero = 15;
  public static final int ERROR = 17;
  public static final int ID = 5;
  public static final int COMILLAS = 14;
  public static final int DOS_PUNTOS = 12;
  public static final int COMA = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Id = 16;
  public static final int IMAGENES = 4;
  public static final int LLAVE_C = 9;
  public static final int LLAVE_A = 8;
  public static final int TIEMPOS = 2;
  public static final int CORCHETE_C = 11;
  public static final int CORCHETE_A = 10;
  public static final int FIN = 7;
  public static final int INICIO = 6;
}

