
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 27 08:43:34 CST 2020
//----------------------------------------------------

package animaciones.Analizadores.Sintactico;

/** CUP generated class containing symbol constants. */
public class SimbolosPintar {
  /* terminals */
  public static final int Entero = 37;
  public static final int MULT = 29;
  public static final int Id = 35;
  public static final int VARS = 2;
  public static final int DIFERENTE = 25;
  public static final int RESTA = 27;
  public static final int CORCHETE_C = 18;
  public static final int INT = 4;
  public static final int CORCHETE_A = 17;
  public static final int LLAVE_C = 16;
  public static final int LLAVE_A = 15;
  public static final int INSTRUCCIONES = 3;
  public static final int AND = 13;
  public static final int IGUAL = 19;
  public static final int OR = 14;
  public static final int DIV = 28;
  public static final int SUMA = 26;
  public static final int IF = 10;
  public static final int PUNTO_COMA = 31;
  public static final int IGUAL_IGUAL = 20;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int PINTAR = 9;
  public static final int COMA = 32;
  public static final int PUNTOS_SEGUIDOS = 30;
  public static final int MENOR = 21;
  public static final int ERROR = 38;
  public static final int MAYOR = 22;
  public static final int ELSE = 11;
  public static final int String = 36;
  public static final int PARENTESIS_C = 34;
  public static final int WHILE = 12;
  public static final int PARENTESIS_A = 33;
  public static final int MAYOR_IGUAL = 23;
  public static final int STRING = 5;
  public static final int MENOR_IGUAL = 24;
  public static final int FALSE = 8;
}

