
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 22 23:58:22 CST 2020
//----------------------------------------------------

package animaciones.Analizadores.Sintactico;

/** CUP generated class containing symbol constants. */
public class SimbolosColores {
  /* terminals */
  public static final int GREEN = 6;
  public static final int COMA = 10;
  public static final int NumHEX = 12;
  public static final int Id = 13;
  public static final int ERROR = 14;
  public static final int LLAVE_C = 8;
  public static final int EOF = 0;
  public static final int COLORES = 2;
  public static final int LLAVE_A = 7;
  public static final int NumRGB = 11;
  public static final int error = 1;
  public static final int BLUE = 5;
  public static final int DOS_PUNTOS = 9;
  public static final int HEX = 3;
  public static final int RED = 4;
}

