
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 22 00:29:55 CST 2020
//----------------------------------------------------

package animaciones.Analizadores.Sintactico;

/** CUP generated class containing symbol constants. */
public class SimbolosLienzo {
  /* terminals */
  public static final int GREEN = 15;
  public static final int TAMAÑO = 4;
  public static final int Entero = 24;
  public static final int NumHEX = 22;
  public static final int ERROR = 26;
  public static final int PNG = 9;
  public static final int BLUE = 14;
  public static final int COMILLAS = 20;
  public static final int RED = 13;
  public static final int DOS_PUNTOS = 18;
  public static final int HEX = 12;
  public static final int TIPO = 8;
  public static final int LIENZOS = 2;
  public static final int COMA = 19;
  public static final int CUADRO = 5;
  public static final int NOMBRE = 3;
  public static final int EOF = 0;
  public static final int FONDO = 11;
  public static final int GIF = 10;
  public static final int Id = 23;
  public static final int error = 1;
  public static final int LLAVE_C = 17;
  public static final int LLAVE_A = 16;
  public static final int DIM_Y = 7;
  public static final int DIM_X = 6;
  public static final int NumRGB = 21;
  public static final int Nombre = 25;
}

