/* The following code was generated by JFlex 1.6.1 */

package animaciones.Analizadores.Lexico;
import java_cup.runtime.Symbol;
import animaciones.Analizadores.Sintactico.SimbolosPintar;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lexicoPintar.jflex</tt>
 */
public class AnalizadorLexicoPintar implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\63\1\64\1\65\1\64\1\64\22\0\1\62\1\2\1\60"+
    "\4\2\1\0\1\42\1\43\1\54\1\51\1\57\1\52\1\55\1\53"+
    "\12\3\1\0\1\56\1\47\1\46\1\50\1\0\1\2\1\5\1\1"+
    "\1\14\1\37\1\16\3\1\1\10\4\1\1\11\1\15\1\34\1\1"+
    "\1\6\1\7\1\12\1\13\1\4\4\1\1\44\1\0\1\45\1\0"+
    "\1\61\1\0\1\30\1\24\2\1\1\27\1\32\1\23\1\36\1\17"+
    "\2\1\1\26\1\1\1\20\1\25\2\1\1\22\1\33\1\21\1\31"+
    "\1\1\1\35\3\1\1\40\1\0\1\41\7\0\1\65\u1f97\0\1\60"+
    "\12\0\1\65\1\65\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\14\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\1\1\21\1\22\1\1\1\23\4\2"+
    "\1\24\1\2\1\25\6\2\1\26\1\27\1\30\1\31"+
    "\2\0\1\32\1\0\1\2\1\33\2\2\1\34\6\2"+
    "\1\35\1\0\1\36\1\37\2\2\1\40\1\2\1\41"+
    "\3\2\1\0\3\2\1\42\1\2\1\43\1\35\1\44"+
    "\2\2\1\45\1\2\1\46\5\2\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\u0360\0\u0396"+
    "\0\u03cc\0\66\0\66\0\u0402\0\66\0\u0438\0\66\0\66"+
    "\0\u046e\0\66\0\u04a4\0\u04da\0\u0510\0\u0546\0\154\0\u057c"+
    "\0\154\0\u05b2\0\u05e8\0\u061e\0\u0654\0\u068a\0\u06c0\0\66"+
    "\0\66\0\66\0\66\0\u06f6\0\u072c\0\66\0\u0762\0\u0798"+
    "\0\154\0\u07ce\0\u0804\0\154\0\u083a\0\u0870\0\u08a6\0\u08dc"+
    "\0\u0912\0\u0948\0\u06f6\0\u097e\0\66\0\154\0\u09b4\0\u09ea"+
    "\0\154\0\u0a20\0\154\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e"+
    "\0\u0b64\0\u0b9a\0\154\0\u0bd0\0\154\0\66\0\154\0\u0c06"+
    "\0\u0c3c\0\154\0\u0c72\0\154\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a"+
    "\0\u0d80\0\154";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\3\1\7"+
    "\1\10\4\3\1\11\1\3\1\12\1\3\1\13\2\3"+
    "\1\14\2\3\1\15\2\3\1\16\1\3\1\17\1\20"+
    "\2\3\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\3\3\42\70\0\1\3\1\0\35\3"+
    "\21\0\1\3\7\0\1\4\63\0\1\3\1\0\2\3"+
    "\1\43\32\3\21\0\1\3\5\0\1\3\1\0\6\3"+
    "\1\44\26\3\21\0\1\3\5\0\1\3\1\0\16\3"+
    "\1\45\16\3\21\0\1\3\5\0\1\3\1\0\6\3"+
    "\1\46\26\3\21\0\1\3\5\0\1\3\1\0\3\3"+
    "\1\47\31\3\21\0\1\3\5\0\1\3\1\0\15\3"+
    "\1\50\11\3\1\51\5\3\21\0\1\3\5\0\1\3"+
    "\1\0\17\3\1\52\15\3\21\0\1\3\5\0\1\3"+
    "\1\0\22\3\1\53\12\3\21\0\1\3\5\0\1\3"+
    "\1\0\23\3\1\54\11\3\21\0\1\3\5\0\1\3"+
    "\1\0\25\3\1\55\7\3\21\0\1\3\5\0\1\3"+
    "\1\0\5\3\1\56\27\3\21\0\1\3\5\0\1\3"+
    "\1\0\33\3\1\57\1\3\21\0\1\3\52\0\1\60"+
    "\65\0\1\61\1\0\1\62\63\0\1\63\72\0\1\64"+
    "\1\65\66\0\1\66\11\0\37\67\14\0\1\67\4\0"+
    "\2\67\4\0\1\3\1\0\3\3\1\70\31\3\21\0"+
    "\1\3\5\0\1\3\1\0\34\3\1\71\21\0\1\3"+
    "\5\0\1\3\1\0\17\3\1\72\15\3\21\0\1\3"+
    "\5\0\1\3\1\0\4\3\1\73\30\3\21\0\1\3"+
    "\5\0\1\3\1\0\16\3\1\74\16\3\21\0\1\3"+
    "\5\0\1\3\1\0\26\3\1\75\6\3\21\0\1\3"+
    "\5\0\1\3\1\0\22\3\1\76\12\3\21\0\1\3"+
    "\5\0\1\3\1\0\30\3\1\77\4\3\21\0\1\3"+
    "\5\0\1\3\1\0\23\3\1\100\11\3\21\0\1\3"+
    "\5\0\1\3\1\0\6\3\1\101\26\3\21\0\1\3"+
    "\5\0\1\3\1\0\14\3\1\102\20\3\21\0\1\3"+
    "\5\0\37\103\14\0\1\103\5\0\2\103\3\0\37\104"+
    "\14\0\1\104\5\0\3\104\2\0\37\67\14\0\1\67"+
    "\3\0\1\105\2\67\4\0\1\3\1\0\4\3\1\106"+
    "\30\3\21\0\1\3\5\0\1\3\1\0\14\3\1\107"+
    "\20\3\21\0\1\3\5\0\1\3\1\0\7\3\1\110"+
    "\25\3\21\0\1\3\5\0\1\3\1\0\24\3\1\111"+
    "\10\3\21\0\1\3\5\0\1\3\1\0\23\3\1\112"+
    "\11\3\21\0\1\3\5\0\1\3\1\0\24\3\1\113"+
    "\10\3\21\0\1\3\5\0\1\3\1\0\30\3\1\114"+
    "\4\3\21\0\1\3\5\0\1\3\1\0\7\3\1\115"+
    "\25\3\21\0\1\3\5\0\1\3\1\0\23\3\1\116"+
    "\11\3\21\0\1\3\5\0\37\104\14\0\1\117\5\0"+
    "\3\104\2\0\1\3\1\0\15\3\1\120\17\3\21\0"+
    "\1\3\5\0\1\3\1\0\3\3\1\121\31\3\21\0"+
    "\1\3\5\0\1\3\1\0\24\3\1\122\10\3\21\0"+
    "\1\3\5\0\1\3\1\0\24\3\1\123\10\3\21\0"+
    "\1\3\5\0\1\3\1\0\2\3\1\124\32\3\21\0"+
    "\1\3\5\0\1\3\1\0\24\3\1\125\10\3\21\0"+
    "\1\3\5\0\37\104\13\0\1\126\1\117\5\0\3\104"+
    "\2\0\1\3\1\0\20\3\1\127\14\3\21\0\1\3"+
    "\5\0\1\3\1\0\10\3\1\130\24\3\21\0\1\3"+
    "\5\0\1\3\1\0\25\3\1\131\7\3\21\0\1\3"+
    "\5\0\1\3\1\0\3\3\1\132\31\3\21\0\1\3"+
    "\5\0\1\3\1\0\11\3\1\133\23\3\21\0\1\3"+
    "\5\0\1\3\1\0\15\3\1\134\17\3\21\0\1\3"+
    "\5\0\1\3\1\0\11\3\1\135\23\3\21\0\1\3"+
    "\5\0\1\3\1\0\5\3\1\136\27\3\21\0\1\3"+
    "\5\0\1\3\1\0\12\3\1\137\22\3\21\0\1\3"+
    "\5\0\1\3\1\0\6\3\1\140\26\3\21\0\1\3"+
    "\5\0\1\3\1\0\13\3\1\141\21\3\21\0\1\3"+
    "\5\0\1\3\1\0\4\3\1\142\30\3\21\0\1\3"+
    "\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3510];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\16\1\6\11\3\1\2\11\1\1\1\11"+
    "\1\1\2\11\1\1\1\11\15\1\4\11\2\0\1\11"+
    "\1\0\14\1\1\0\1\11\11\1\1\0\6\1\1\11"+
    "\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexicoPintar(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(SimbolosPintar.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("ERROR "+yyline);return new Symbol(SimbolosPintar.ERROR,yycolumn,yyline,yytext());
            }
          case 40: break;
          case 2: 
            { return new Symbol(SimbolosPintar.Id, yycolumn,yyline,yytext());
            }
          case 41: break;
          case 3: 
            { return new Symbol(SimbolosPintar.Entero, yycolumn,yyline,yytext());
            }
          case 42: break;
          case 4: 
            { return new Symbol(SimbolosPintar.LLAVE_A, yycolumn,yyline,yytext());
            }
          case 43: break;
          case 5: 
            { return new Symbol(SimbolosPintar.LLAVE_C, yycolumn,yyline,yytext());
            }
          case 44: break;
          case 6: 
            { return new Symbol(SimbolosPintar.PARENTESIS_A, yycolumn,yyline,yytext());
            }
          case 45: break;
          case 7: 
            { return new Symbol(SimbolosPintar.PARENTESIS_C, yycolumn,yyline,yytext());
            }
          case 46: break;
          case 8: 
            { return new Symbol(SimbolosPintar.CORCHETE_A, yycolumn,yyline,yytext());
            }
          case 47: break;
          case 9: 
            { return new Symbol(SimbolosPintar.CORCHETE_C, yycolumn,yyline,yytext());
            }
          case 48: break;
          case 10: 
            { return new Symbol(SimbolosPintar.IGUAL, yycolumn,yyline,yytext());
            }
          case 49: break;
          case 11: 
            { return new Symbol(SimbolosPintar.MENOR, yycolumn,yyline,yytext());
            }
          case 50: break;
          case 12: 
            { return new Symbol(SimbolosPintar.MAYOR, yycolumn,yyline,yytext());
            }
          case 51: break;
          case 13: 
            { return new Symbol(SimbolosPintar.SUMA, yycolumn,yyline,yytext());
            }
          case 52: break;
          case 14: 
            { return new Symbol(SimbolosPintar.RESTA, yycolumn,yyline,yytext());
            }
          case 53: break;
          case 15: 
            { return new Symbol(SimbolosPintar.DIV, yycolumn,yyline,yytext());
            }
          case 54: break;
          case 16: 
            { return new Symbol(SimbolosPintar.MULT, yycolumn,yyline,yytext());
            }
          case 55: break;
          case 17: 
            { return new Symbol(SimbolosPintar.PUNTO_COMA, yycolumn,yyline,yytext());
            }
          case 56: break;
          case 18: 
            { return new Symbol(SimbolosPintar.COMA, yycolumn,yyline,yytext());
            }
          case 57: break;
          case 19: 
            { 
            }
          case 58: break;
          case 20: 
            { return new Symbol(SimbolosPintar.OR, yycolumn,yyline,yytext());
            }
          case 59: break;
          case 21: 
            { return new Symbol(SimbolosPintar.IF, yycolumn,yyline,yytext());
            }
          case 60: break;
          case 22: 
            { return new Symbol(SimbolosPintar.IGUAL_IGUAL, yycolumn,yyline,yytext());
            }
          case 61: break;
          case 23: 
            { return new Symbol(SimbolosPintar.MENOR_IGUAL, yycolumn,yyline,yytext());
            }
          case 62: break;
          case 24: 
            { return new Symbol(SimbolosPintar.DIFERENTE, yycolumn,yyline,yytext());
            }
          case 63: break;
          case 25: 
            { return new Symbol(SimbolosPintar.MAYOR_IGUAL, yycolumn,yyline,yytext());
            }
          case 64: break;
          case 26: 
            { return new Symbol(SimbolosPintar.PUNTOS_SEGUIDOS, yycolumn,yyline,yytext());
            }
          case 65: break;
          case 27: 
            { return new Symbol(SimbolosPintar.AND, yycolumn,yyline,yytext());
            }
          case 66: break;
          case 28: 
            { return new Symbol(SimbolosPintar.INT, yycolumn,yyline,yytext());
            }
          case 67: break;
          case 29: 
            { System.out.println("COMENTARIO"+yyline);
            }
          case 68: break;
          case 30: 
            { return new Symbol(SimbolosPintar.String, yycolumn,yyline,yytext());
            }
          case 69: break;
          case 31: 
            { return new Symbol(SimbolosPintar.VARS, yycolumn,yyline,yytext());
            }
          case 70: break;
          case 32: 
            { return new Symbol(SimbolosPintar.TRUE, yycolumn,yyline,yytext());
            }
          case 71: break;
          case 33: 
            { return new Symbol(SimbolosPintar.ELSE, yycolumn,yyline,yytext());
            }
          case 72: break;
          case 34: 
            { return new Symbol(SimbolosPintar.FALSE, yycolumn,yyline,yytext());
            }
          case 73: break;
          case 35: 
            { return new Symbol(SimbolosPintar.WHILE, yycolumn,yyline,yytext());
            }
          case 74: break;
          case 36: 
            { return new Symbol(SimbolosPintar.STRING, yycolumn,yyline,yytext());
            }
          case 75: break;
          case 37: 
            { return new Symbol(SimbolosPintar.PINTAR, yycolumn,yyline,yytext());
            }
          case 76: break;
          case 38: 
            { return new Symbol(SimbolosPintar.BOOLEAN, yycolumn,yyline,yytext());
            }
          case 77: break;
          case 39: 
            { return new Symbol(SimbolosPintar.INSTRUCCIONES, yycolumn,yyline,yytext());
            }
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface SimbolosPintar
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = SimbolosPintar.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalizadorLexicoPintar [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalizadorLexicoPintar scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalizadorLexicoPintar(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
